### ISSUE TITLE
TODO unification of "identical" files in mesher and solver

### ISSUE THREAD

**Issue by martinvandriel** [geodynamics/axisem#22]
- [ ] analytic_spheroid_mapping.f90 should be doing the same, but is quite different, needs testing
- [x] splib.f90 has changed some of the interfaces. Probably its best to compute everythin gll/glj related in the mesher and store it in the meshfile, then the whole splib can be removed from the solver
- [x] clocks.f90 should also be unified
